# Generated by Django 4.0.8 on 2023-03-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_email',
            field=models.CharField(blank=True, default=False, max_length=90, null=True),
        ),
    ]
